# Generated by Django 2.2.2 on 2019-06-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech_used',
            field=models.ManyToManyField(help_text='Tech Used in project', to='catalog.Technology'),
        ),
    ]
