# Generated by Django 2.2.2 on 2019-06-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190630_0434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fName',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lName',
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, help_text="Enter student's last name", max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Started'),
        ),
    ]
