# Generated by Django 2.2.2 on 2019-07-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_student_disp_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='disp_pic',
            field=models.ImageField(null=True, upload_to='static/users/'),
        ),
    ]
